"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

env_repo = Path(__file__).resolve().parents[2] / '.env'
env_server = Path(__file__).resolve().parent.parent / '.env'
if env_repo.exists():
    load_dotenv(env_repo)
elif env_server.exists():
    load_dotenv(env_server)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-%vk!2xm+@%3i+glrt@9qgsme*6bfn9an-=md6h#!hayj2(z0p^')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = [
    'smartpark-undergrad-project.onrender.com',
    'smartpark-theta.vercel.app', 
    'localhost',
    '127.0.0.1',
]

# CORS Settings - Fixed the frontend domain typo
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'https://smartpark-theta.vercel.app',
    'https://smartpark-undergrad-project.onrender.com'
]

# Additional CORS settings for preflight requests
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# CSRF settings to match CORS
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
    'https://smartpark-theta.vercel.app',
    'https://smartpark-undergrad-project.onrender.com'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'car',
    'django_q',
    # Django REST framework and token auth
    'rest_framework',
    'rest_framework.authtoken',
    # CORS headers
    'corsheaders',
]

# Use the custom user model from the car app
AUTH_USER_MODEL = 'car.User'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DEFAULT_SQLITE = {
    'ENGINE': 'django.db.backends.sqlite3',
    'NAME': BASE_DIR / 'db.sqlite3',
}

# Use DATABASE_URL from environment if provided, otherwise fall back to SQLite
database_url = os.environ.get('DATABASE_URL')
if database_url:
    DATABASES = {
        'default': dj_database_url.parse(database_url, conn_max_age=600)
    }
else:
    DATABASES = {'default': DEFAULT_SQLITE}


# Caching configuration: prefer Redis if REDIS_URL is provided, otherwise use local memory cache.
REDIS_URL = os.environ.get('REDIS_URL')
if REDIS_URL:
    # django-redis recommended configuration. If django-redis isn't installed
    # the project should install it for production performance.
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                # 'PASSWORD': os.environ.get('REDIS_PASSWORD', None),
            }
        }
    }
else:
    # Lightweight in-memory cache for development and small deployments
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Directory where `collectstatic` will collect static files for deployment
# Must be a filesystem path when using the staticfiles app (required by collectstatic)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Additional locations the staticfiles app will traverse (optional)
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# --- Load .env file for local development ---
import os
from dotenv import load_dotenv
load_dotenv(os.path.join(os.path.dirname(__file__), '../.env'))

# Public site URL used for building absolute links when request is not available
# Set via environment in production, e.g. SITE_URL=https://your-app.onrender.com
SITE_URL = os.environ.get('SITE_URL')

# Cloudinary configuration (optional). Use environment variables on production.
# If CLOUDINARY_URL or CLOUDINARY_API_KEY/CLOUDINARY_API_SECRET are present,
# enable Cloudinary storage for media files.
if os.environ.get('CLOUDINARY_URL') or os.environ.get('CLOUDINARY_API_KEY'):
    # add cloudinary apps if not already present
    if 'cloudinary' not in INSTALLED_APPS:
        INSTALLED_APPS += ['cloudinary', 'cloudinary_storage']


    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME') or os.environ.get('CLOUD_NAME'),
        'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
        'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
        'RESOURCE_TYPE': 'auto',
        'UPLOAD_OPTIONS': {
            'resource_type': 'auto',
            'type': 'upload',
            'access_mode': 'public',
        },
    }

    # Use Cloudinary for storing uploaded media
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

    # When using cloudinary storage, FileField.url will return a cloud URL.
    # MEDIA_URL can remain as-is; cloudinary_storage will generate secure URLs.

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework configuration - enable TokenAuthentication
REST_FRAMEWORK = {
    # Allow unauthenticated access by default for browsable API and public endpoints,
    # but views that declare permission_classes=[IsAuthenticated] will require auth.
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}
# Django-Q configuration
Q_CLUSTER = {
    'name': 'FinalQ',
    'workers': 2,
    'recycle': 500,
    'timeout': 60,
    'retry': 120,
    'queue_limit': 50,
    'bulk': 10,
    'orm': 'default',
}