# Generated by Django 5.1.3 on 2025-10-15 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_payment_paid_at_payment_stripe_payment_intent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='payment_id',
            new_name='transaction_id',
        ),
    ]
