# Generated by Django 5.1.3 on 2025-10-15 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_rename_payment_id_booking_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='Payment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='car.payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='slot_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.parkingslot'),
        ),
    ]
