# Generated by Django 5.1.3 on 2025-10-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_alter_parkingslot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='manual_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='type',
            field=models.CharField(choices=[('regular', 'Regular'), ('premium', 'Premium'), ('vip', 'VIP')], max_length=10),
        ),
    ]
