# Generated by Django 4.2.25 on 2025-11-05 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_parkingslot_manual_locked_alter_parkingslot_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='vehicle_type',
        ),
    ]
