# Generated by Django 4.2.25 on 2025-11-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_add_archived_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('booking_confirmation', 'Booking Confirmation'), ('booking_reminder', 'Booking Reminder'), ('payment_receipt', 'Payment Receipt'), ('booking_expiry', 'Booking Expiry'), ('booking_expired', 'Booking Expired'), ('user_registered', 'User Registered')], max_length=50),
        ),
    ]
