# Generated by Django 4.2.25 on 2025-11-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0013_booking_archived_payment_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('booking_confirmation', 'Booking Confirmation'), ('new_booking', 'New Booking'), ('booking_reminder', 'Booking Reminder'), ('payment_receipt', 'Payment Receipt'), ('payment_succeeded', 'Payment Succeeded'), ('booking_expiry', 'Booking Expiry'), ('booking_expired', 'Booking Expired'), ('user_registered', 'User Registered')], max_length=50),
        ),
    ]
