# Generated by Django 4.2.25 on 2025-11-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0014_booking_archived_payment_archived_and_more'),
    ]

    operations = [
        migrations.RunPython(
            code=lambda apps, schema_editor: (
                (lambda Booking, ParkingSlot: (
                    Booking.objects.filter(slot_id__isnull=True).update(slot_id=(ParkingSlot.objects.first().id if ParkingSlot.objects.exists() else None)) if ParkingSlot.objects.exists() else Booking.objects.filter(slot_id__isnull=True).delete()
                ))(apps.get_model('car', 'Booking'), apps.get_model('car', 'ParkingSlot'))
            ),
            reverse_code=migrations.RunPython.noop,
        ),
        # Removed duplicate AddField for 'archived' columns; already added by previous migration
    ]
