# Generated by Django 4.2.25 on 2025-11-18 19:04

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('car', '0015_booking_archived_payment_archived'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='booking',
                    name='archived',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='payment',
                    name='archived',
                    field=models.BooleanField(default=False),
                ),
            ],
        ),
    ]
