# Generated by Django 4.2.25 on 2026-01-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0016_booking_archived_payment_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('operator', 'Operator'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
