# Generated by Django 4.2.25 on 2026-02-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0018_ticketmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='subject',
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='open', max_length=20),
        ),
    ]
