# Generated by Django 4.2.25 on 2026-03-15 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0019_remove_ticket_subject_ticketmessage_is_read_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketDeletedBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_by', to='car.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-deleted_at'],
                'unique_together': {('ticket', 'user')},
            },
        ),
    ]
